GET http://localhost:3000/api/threads/

###
GET http://localhost:3000/api/threads/64c1065e27d15c4882e2e35d
###

POST http://localhost:3000/api/threads/
Content-Type: application/json

{
  "opName": "Admin",
  "subject": "Test!",
  "comment": "Currently testing post...",
  "image": "https://www.etudes-en-france.net/wp-content/uploads/2018/07/test.jpg"
}
