GET http://localhost:3000/api/threads/

###
GET http://localhost:3000/api/threads/64c1065e27d15c4882e2e35d
###

POST http://localhost:3000/api/threads/
Content-Type: application/json

{
  "opName": "Admin",
  "subject": ":D",
  "comment": ":|",
  "image": "https://as1.ftcdn.net/v2/jpg/02/42/27/70/1000_F_242277080_co93xxrF8alcqCBldi3UzQks49OyRMKu.jpg"
}

###
PATCH http://localhost:3000/api/threads/64c23d3349a0171ce98de928
Content-Type: application/json

{
  "comment":"Testing ?"
}

